<?php

/*
 * Copyright (c) 2025-2026 Netresearch DTT GmbH
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

declare(strict_types=1);

/**
 * Demo data for nr_llm — the record graph behind demos, documentation
 * screenshots and manual testing.
 *
 * Relations are named by IDENTIFIER, never by uid. The SQL this replaces resolved
 * them through MySQL session variables that looked up 'whatever is default right
 * now', so the graph depended on insert order and on flags it did not set itself.
 *
 * Two streams on purpose. The local Ollama graph is what an evaluator installs
 * and costs nothing, so every cost surface reads 0.00 from it alone — a
 * functional test caught exactly that. The `demo-*` records carry real list
 * prices (cost_input/cost_output are CENTS per 1M tokens, as Model::
 * getCostInputDollars() divides by 100) and ship INACTIVE, so they price the
 * usage history without offering themselves as a usable provider.
 *
 * @return array{providers: list<array<string, mixed>>, models: list<array<string, mixed>>, configurations: list<array<string, mixed>>, tasks: list<array<string, mixed>>}
 */
return [
    'providers' => [
        [
            'identifier' => 'ollama-local',
            'name' => 'Local Ollama',
            'description' => 'Local Ollama LLM server on the container network. No API key required.',
            'adapter_type' => 'ollama',
            // http, not https, and deliberately so: this is a container-internal
            // hostname on a private network, and Ollama serves no TLS — the
            // upstream project has no HTTPS listener to point at. Rewriting the
            // scheme to satisfy a clear-text-protocol rule would leave a demo
            // provider that cannot connect. Flagged by SonarCloud on #879 and
            // kept.
            'endpoint_url' => 'http://ollama:11434',
            'api_key' => '',
            'api_timeout' => 120,
            'max_retries' => 3,
            'is_active' => 1,
            'priority' => 100,
            'sorting' => 10,
        ],
        [
            'identifier' => 'demo-openai',
            'name' => 'Demo OpenAI',
            'description' => 'Demo provider — priced, so the analytics surfaces show a real figure.',
            'adapter_type' => 'openai',
            'endpoint_url' => '',
            'api_key' => '',
            'api_timeout' => 120,
            'max_retries' => 2,
            'is_active' => 0,
            'priority' => 20,
            'sorting' => 20,
        ],
        [
            'identifier' => 'demo-anthropic',
            'name' => 'Demo Anthropic',
            'description' => 'Demo provider — priced, so the analytics surfaces show a real figure.',
            'adapter_type' => 'claude',
            'endpoint_url' => '',
            'api_key' => '',
            'api_timeout' => 120,
            'max_retries' => 2,
            'is_active' => 0,
            'priority' => 30,
            'sorting' => 30,
        ],
        [
            'identifier' => 'demo-google',
            'name' => 'Demo Google',
            'description' => 'Demo provider — priced, so the analytics surfaces show a real figure.',
            'adapter_type' => 'gemini',
            'endpoint_url' => '',
            'api_key' => '',
            'api_timeout' => 120,
            'max_retries' => 2,
            'is_active' => 0,
            'priority' => 40,
            'sorting' => 40,
        ],
    ],
    'models' => [
        [
            'identifier' => 'qwen3-4b',
            'name' => 'Qwen 3 4B',
            'description' => 'Alibaba Qwen 3 with 4B parameters. Tool-capable, good general purpose at a small footprint (~2.5GB, ~4GB RAM). April 2025 release.',
            'provider' => 'ollama-local',
            'model_id' => 'qwen3:4b',
            'context_length' => 32768,
            'max_output_tokens' => 4096,
            'capabilities' => 'chat,completion,streaming,tools',
            'default_timeout' => 90,
            'cost_input' => 0,
            'cost_output' => 0,
            'is_active' => 1,
            'is_default' => 1,
            'sorting' => 10,
        ],
        [
            'identifier' => 'gemma3-1b',
            'name' => 'Gemma 3 1B',
            'description' => 'Google Gemma 3 with 1B parameters. Good quality for its size. February 2025 release.',
            'provider' => 'ollama-local',
            'model_id' => 'gemma3:1b',
            'context_length' => 32768,
            'max_output_tokens' => 4096,
            'capabilities' => 'chat,completion,streaming',
            'default_timeout' => 60,
            'cost_input' => 0,
            'cost_output' => 0,
            'is_active' => 1,
            'is_default' => 0,
            'sorting' => 20,
        ],
        [
            'identifier' => 'smollm2-360m',
            'name' => 'SmolLM2 360M',
            'description' => 'Hugging Face SmolLM2 with 360M parameters. Ultra-fast, minimal resources.',
            'provider' => 'ollama-local',
            'model_id' => 'smollm2:360m',
            'context_length' => 8192,
            'max_output_tokens' => 2048,
            'capabilities' => 'chat,completion',
            'default_timeout' => 30,
            'cost_input' => 0,
            'cost_output' => 0,
            'is_active' => 1,
            'is_default' => 0,
            'sorting' => 30,
        ],
        [
            'identifier' => 'demo-gpt-4o',
            'name' => 'GPT-4o',
            'description' => 'Demo model. cost_input/cost_output are CENTS per 1M tokens.',
            'provider' => 'demo-openai',
            'model_id' => 'gpt-4o',
            'context_length' => 128000,
            'max_output_tokens' => 4096,
            'capabilities' => 'chat,completion',
            'default_timeout' => 120,
            'cost_input' => 250,
            'cost_output' => 1000,
            'is_active' => 0,
            'is_default' => 0,
            'sorting' => 110,
        ],
        [
            'identifier' => 'demo-gpt-4o-mini',
            'name' => 'GPT-4o mini',
            'description' => 'Demo model. cost_input/cost_output are CENTS per 1M tokens.',
            'provider' => 'demo-openai',
            'model_id' => 'gpt-4o-mini',
            'context_length' => 128000,
            'max_output_tokens' => 4096,
            'capabilities' => 'chat,completion',
            'default_timeout' => 120,
            'cost_input' => 15,
            'cost_output' => 60,
            'is_active' => 0,
            'is_default' => 0,
            'sorting' => 120,
        ],
        [
            'identifier' => 'demo-claude-3-7-sonnet',
            'name' => 'Claude 3.7 Sonnet',
            'description' => 'Demo model. cost_input/cost_output are CENTS per 1M tokens.',
            'provider' => 'demo-anthropic',
            'model_id' => 'claude-3-7-sonnet',
            'context_length' => 128000,
            'max_output_tokens' => 4096,
            'capabilities' => 'chat,completion',
            'default_timeout' => 120,
            'cost_input' => 300,
            'cost_output' => 1500,
            'is_active' => 0,
            'is_default' => 0,
            'sorting' => 130,
        ],
        [
            'identifier' => 'demo-gemini-2-5-flash',
            'name' => 'Gemini 2.5 Flash',
            'description' => 'Demo model. cost_input/cost_output are CENTS per 1M tokens.',
            'provider' => 'demo-google',
            'model_id' => 'gemini-2.5-flash',
            'context_length' => 128000,
            'max_output_tokens' => 4096,
            'capabilities' => 'chat,completion',
            'default_timeout' => 120,
            'cost_input' => 30,
            'cost_output' => 120,
            'is_active' => 0,
            'is_default' => 0,
            'sorting' => 140,
        ],
    ],
    'configurations' => [
        [
            'identifier' => 'local-general',
            'name' => 'Local General Purpose',
            'description' => 'General-purpose configuration for local development and testing.',
            'model' => 'qwen3-4b',
            'system_prompt' => 'You are a helpful AI assistant. Provide clear, accurate, and concise responses.',
            'temperature' => 0.7,
            'max_tokens' => 2048,
            'top_p' => 0.9,
            'timeout' => 0,
            'is_active' => 1,
            'is_default' => 1,
            'sorting' => 10,
        ],
        [
            'identifier' => 'local-summarizer',
            'name' => 'Local Content Summarizer',
            'description' => 'Optimized for summarizing articles, documents, and content.',
            'model' => 'qwen3-4b',
            'system_prompt' => 'You are a content summarizer. Create clear, concise summaries that capture the key points. Focus on the most important information and maintain the original meaning.',
            'temperature' => 0.3,
            'max_tokens' => 1024,
            'top_p' => 0.85,
            'timeout' => 0,
            'is_active' => 1,
            'is_default' => 0,
            'sorting' => 20,
        ],
        [
            'identifier' => 'local-creative',
            'name' => 'Local Creative Writing',
            'description' => 'Higher temperature for creative content generation.',
            'model' => 'qwen3-4b',
            'system_prompt' => 'You are a creative writing assistant. Help generate engaging, imaginative content with varied vocabulary and interesting prose.',
            'temperature' => 0.9,
            'max_tokens' => 2048,
            'top_p' => 0.95,
            'timeout' => 120,
            'is_active' => 1,
            'is_default' => 0,
            'sorting' => 30,
        ],
        [
            'identifier' => 'local-code',
            'name' => 'Local Code Assistant',
            'description' => 'Low temperature for precise code generation and explanations.',
            'model' => 'qwen3-4b',
            'system_prompt' => 'You are a code assistant. Provide accurate, well-formatted code with clear explanations. Follow best practices and coding standards.',
            'temperature' => 0.2,
            'max_tokens' => 4096,
            'top_p' => 0.8,
            'timeout' => 180,
            'is_active' => 1,
            'is_default' => 0,
            'sorting' => 40,
        ],
        [
            'identifier' => 'demo-cfg-gpt4o',
            'name' => 'Demo GPT-4o Chat',
            'description' => 'Demo configuration for the priced analytics stream.',
            'model' => 'demo-gpt-4o',
            'system_prompt' => '',
            'temperature' => '0.70',
            'max_tokens' => 2048,
            'top_p' => '1.00',
            'timeout' => 120,
            'is_active' => 0,
            'is_default' => 0,
            'sorting' => 110,
        ],
        [
            'identifier' => 'demo-cfg-gpt4o-mini',
            'name' => 'Demo GPT-4o mini',
            'description' => 'Demo configuration for the priced analytics stream.',
            'model' => 'demo-gpt-4o-mini',
            'system_prompt' => '',
            'temperature' => '0.70',
            'max_tokens' => 2048,
            'top_p' => '1.00',
            'timeout' => 120,
            'is_active' => 0,
            'is_default' => 0,
            'sorting' => 120,
        ],
        [
            'identifier' => 'demo-cfg-claude',
            'name' => 'Demo Claude Sonnet',
            'description' => 'Demo configuration for the priced analytics stream.',
            'model' => 'demo-claude-3-7-sonnet',
            'system_prompt' => '',
            'temperature' => '0.70',
            'max_tokens' => 2048,
            'top_p' => '1.00',
            'timeout' => 120,
            'is_active' => 0,
            'is_default' => 0,
            'sorting' => 130,
        ],
        [
            'identifier' => 'demo-cfg-gemini',
            'name' => 'Demo Gemini Flash',
            'description' => 'Demo configuration for the priced analytics stream.',
            'model' => 'demo-gemini-2-5-flash',
            'system_prompt' => '',
            'temperature' => '0.70',
            'max_tokens' => 2048,
            'top_p' => '1.00',
            'timeout' => 120,
            'is_active' => 0,
            'is_default' => 0,
            'sorting' => 140,
        ],
    ],
    'tasks' => [
        [
            'identifier' => 'analyze-syslog',
            'name' => 'Analyze System Log Errors',
            'description' => 'Reviews TYPO3 sys_log entries and identifies patterns, critical errors, and potential issues.',
            'category' => 'log_analysis',
            'configuration' => 'local-general',
            'prompt_template' => 'You are a TYPO3 system administrator assistant. Analyze the following system log entries and provide:' . "\n" . '' . "\n" . '1. **Summary**: Brief overview of the log content' . "\n" . '2. **Critical Issues**: Any errors that need immediate attention' . "\n" . '3. **Patterns**: Recurring problems or suspicious activity' . "\n" . '4. **Recommendations**: Suggested actions to resolve issues' . "\n" . '' . "\n" . 'Focus on actionable insights. Be concise but thorough.' . "\n" . '' . "\n" . 'Log entries:' . "\n" . '```' . "\n" . '{{input}}' . "\n" . '```',
            'input_type' => 'syslog',
            'input_source' => '{"limit": 100, "error_only": true}',
            'output_format' => 'markdown',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 10,
        ],
        [
            'identifier' => 'analyze-deprecation-log',
            'name' => 'Analyze Deprecation Log',
            'description' => 'Reviews TYPO3 deprecation log and suggests upgrade paths for deprecated code.',
            'category' => 'log_analysis',
            'configuration' => 'local-general',
            'prompt_template' => 'You are a TYPO3 upgrade specialist. Analyze the following deprecation log entries and provide:' . "\n" . '' . "\n" . '1. **Summary**: Overview of deprecated functionality being used' . "\n" . '2. **Priority Items**: Deprecations that will break in the next major version' . "\n" . '3. **Migration Guide**: For each unique deprecation, suggest the modern replacement' . "\n" . '4. **Effort Estimate**: Low/Medium/High for addressing each deprecation' . "\n" . '' . "\n" . 'Group similar deprecations together. Focus on what needs to be fixed before the next TYPO3 upgrade.' . "\n" . '' . "\n" . 'Deprecation log:' . "\n" . '```' . "\n" . '{{input}}' . "\n" . '```',
            'input_type' => 'deprecation_log',
            'input_source' => '',
            'output_format' => 'markdown',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 20,
        ],
        [
            'identifier' => 'security-analysis',
            'name' => 'Security Event Analysis',
            'description' => 'Analyzes system logs for potential security issues like failed logins or suspicious activity.',
            'category' => 'log_analysis',
            'configuration' => 'local-general',
            'prompt_template' => 'You are a security analyst reviewing TYPO3 system logs. Analyze for:' . "\n" . '' . "\n" . '1. **Failed Login Attempts**: Look for brute force patterns or credential stuffing' . "\n" . '2. **Unauthorized Access**: Attempts to access restricted areas' . "\n" . '3. **Suspicious Patterns**: Unusual timing, IP addresses, or user agents' . "\n" . '4. **Recommendations**: Security hardening suggestions' . "\n" . '' . "\n" . 'Rate the overall security risk: LOW / MEDIUM / HIGH / CRITICAL' . "\n" . '' . "\n" . 'Log entries:' . "\n" . '```' . "\n" . '{{input}}' . "\n" . '```',
            'input_type' => 'syslog',
            'input_source' => '{"limit": 200, "error_only": false}',
            'output_format' => 'markdown',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 30,
        ],
        [
            'identifier' => 'generate-alt-text',
            'name' => 'Generate Image Alt Text',
            'description' => 'Generates accessible alt text descriptions for images based on context or filename.',
            'category' => 'content',
            'configuration' => 'local-general',
            'prompt_template' => 'Generate concise, accessible alt text for images. The alt text should:' . "\n" . '' . "\n" . '1. Be descriptive but brief (under 125 characters if possible)' . "\n" . '2. Describe the image content, not just "image of..."' . "\n" . '3. Include relevant context for the webpage' . "\n" . '4. Be useful for screen reader users' . "\n" . '' . "\n" . 'For each image or description provided, generate an appropriate alt text.' . "\n" . '' . "\n" . 'Input (image descriptions, filenames, or context):' . "\n" . '{{input}}' . "\n" . '' . "\n" . 'Provide the alt text in a format that can be directly used in HTML alt attributes.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'plain',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 100,
        ],
        [
            'identifier' => 'generate-meta-description',
            'name' => 'Generate Meta Descriptions',
            'description' => 'Creates SEO-optimized meta descriptions for web pages based on content.',
            'category' => 'content',
            'configuration' => 'local-general',
            'prompt_template' => 'Generate an SEO-optimized meta description for a web page. Requirements:' . "\n" . '' . "\n" . '1. Length: 150-160 characters (optimal for search results)' . "\n" . '2. Include relevant keywords naturally' . "\n" . '3. Be compelling and encourage clicks' . "\n" . '4. Accurately summarize the page content' . "\n" . '5. Include a call-to-action if appropriate' . "\n" . '' . "\n" . 'Page content or summary:' . "\n" . '{{input}}' . "\n" . '' . "\n" . 'Provide ONLY the meta description text, ready to use in a <meta name="description"> tag.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'plain',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 110,
        ],
        [
            'identifier' => 'summarize-content',
            'name' => 'Summarize Page Content',
            'description' => 'Creates a concise summary of page content for internal use or teasers.',
            'category' => 'content',
            'configuration' => 'local-general',
            'prompt_template' => 'Summarize the following web page content in 2-3 sentences. The summary should:' . "\n" . '' . "\n" . '1. Capture the main topic and key points' . "\n" . '2. Be suitable for use as a teaser or excerpt' . "\n" . '3. Be engaging and informative' . "\n" . '4. Avoid redundancy' . "\n" . '' . "\n" . 'Content:' . "\n" . '{{input}}' . "\n" . '' . "\n" . 'Provide a clear, concise summary.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'plain',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 120,
        ],
        [
            'identifier' => 'translate-content',
            'name' => 'Translate Content',
            'description' => 'Translates content between languages while maintaining tone and context.',
            'category' => 'content',
            'configuration' => 'local-general',
            'prompt_template' => 'Translate the following content. Guidelines:' . "\n" . '' . "\n" . '1. Maintain the original tone and style' . "\n" . '2. Adapt cultural references appropriately' . "\n" . '3. Preserve formatting (markdown, HTML tags, etc.)' . "\n" . '4. Keep technical terms consistent' . "\n" . '' . "\n" . 'If the target language is not specified, translate to English.' . "\n" . 'Format: "Target language: [language]" or just provide the text for English translation.' . "\n" . '' . "\n" . 'Content to translate:' . "\n" . '{{input}}' . "\n" . '' . "\n" . 'Provide only the translated text.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'plain',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 130,
        ],
        [
            'identifier' => 'analyze-broken-links',
            'name' => 'Analyze Broken Links Report',
            'description' => 'Reviews a list of broken links and suggests fixes or removal strategies.',
            'category' => 'system',
            'configuration' => 'local-general',
            'prompt_template' => 'Analyze the following broken links report and provide:' . "\n" . '' . "\n" . '1. **Priority Fixes**: Links that are most critical to fix (high-traffic pages, important resources)' . "\n" . '2. **Pattern Analysis**: Common issues (moved domains, outdated URLs, typos)' . "\n" . '3. **Suggested Actions**: For each category of broken links, recommend:' . "\n" . '   - Replace with updated URL' . "\n" . '   - Remove the link' . "\n" . '   - Find alternative resource' . "\n" . '   - Archive.org fallback' . "\n" . '4. **Prevention Tips**: How to avoid similar issues' . "\n" . '' . "\n" . 'Broken links report:' . "\n" . '{{input}}' . "\n" . '' . "\n" . 'Format the response for easy action by content editors.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'markdown',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 200,
        ],
        [
            'identifier' => 'review-redirects',
            'name' => 'Review Redirect Chains',
            'description' => 'Analyzes redirect configurations and identifies chains or loops that need optimization.',
            'category' => 'system',
            'configuration' => 'local-general',
            'prompt_template' => 'Analyze the following redirect configurations for issues:' . "\n" . '' . "\n" . '1. **Redirect Chains**: Identify any A→B→C patterns that should be A→C' . "\n" . '2. **Redirect Loops**: Find any circular redirects' . "\n" . '3. **Outdated Redirects**: Redirects pointing to pages that no longer exist' . "\n" . '4. **Performance Issues**: Redirects that add unnecessary latency' . "\n" . '5. **Optimization Suggestions**: Consolidated redirect rules' . "\n" . '' . "\n" . 'Redirect data:' . "\n" . '{{input}}' . "\n" . '' . "\n" . 'Provide specific recommendations for each issue found.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'markdown',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 210,
        ],
        [
            'identifier' => 'explain-tca',
            'name' => 'Explain TCA Configuration',
            'description' => 'Explains TYPO3 TCA (Table Configuration Array) settings in plain language.',
            'category' => 'developer',
            'configuration' => 'local-general',
            'prompt_template' => 'You are a TYPO3 expert. Explain the following TCA (Table Configuration Array) configuration in plain language.' . "\n" . '' . "\n" . 'For each significant setting, explain:' . "\n" . '1. What it does' . "\n" . '2. Why it might be configured this way' . "\n" . '3. Common use cases' . "\n" . '4. Any potential issues or improvements' . "\n" . '' . "\n" . 'If there are errors or deprecated settings, point them out.' . "\n" . '' . "\n" . 'TCA Configuration:' . "\n" . '```php' . "\n" . '{{input}}' . "\n" . '```' . "\n" . '' . "\n" . 'Provide a clear explanation suitable for intermediate TYPO3 developers.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'markdown',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 300,
        ],
        [
            'identifier' => 'fix-typoscript',
            'name' => 'Suggest TypoScript Fixes',
            'description' => 'Analyzes TypoScript code and suggests fixes for common issues.',
            'category' => 'developer',
            'configuration' => 'local-general',
            'prompt_template' => 'You are a TYPO3 TypoScript expert. Analyze the following TypoScript configuration for issues:' . "\n" . '' . "\n" . '1. **Syntax Errors**: Missing brackets, incorrect property assignments' . "\n" . '2. **Deprecated Settings**: Settings that should be updated for modern TYPO3' . "\n" . '3. **Performance Issues**: Inefficient configurations' . "\n" . '4. **Best Practices**: Suggest improvements' . "\n" . '' . "\n" . 'For each issue, provide:' . "\n" . '- The problem' . "\n" . '- The fix' . "\n" . '- Corrected TypoScript code' . "\n" . '' . "\n" . 'TypoScript Code:' . "\n" . '```typoscript' . "\n" . '{{input}}' . "\n" . '```' . "\n" . '' . "\n" . 'Provide clear, actionable fixes.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'markdown',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 310,
        ],
        [
            'identifier' => 'analyze-fluid',
            'name' => 'Analyze Fluid Template Issues',
            'description' => 'Reviews Fluid templates for errors, accessibility issues, and best practices.',
            'category' => 'developer',
            'configuration' => 'local-general',
            'prompt_template' => 'You are a TYPO3 Fluid template expert. Analyze the following Fluid template for:' . "\n" . '' . "\n" . '1. **Syntax Errors**: Invalid ViewHelper usage, missing closures' . "\n" . '2. **Accessibility Issues**: Missing alt text, improper heading structure, ARIA issues' . "\n" . '3. **Performance**: Inefficient iterations, unnecessary ViewHelper calls' . "\n" . '4. **Best Practices**: XSS prevention, proper escaping, clean code' . "\n" . '5. **TYPO3 Conventions**: Correct namespace usage, standard ViewHelpers' . "\n" . '' . "\n" . 'Fluid Template:' . "\n" . '```html' . "\n" . '{{input}}' . "\n" . '```' . "\n" . '' . "\n" . 'Provide specific fixes with corrected code examples.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'markdown',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 320,
        ],
        [
            'identifier' => 'generate-docs',
            'name' => 'Generate Extension Documentation',
            'description' => 'Creates documentation for TYPO3 extension classes or features.',
            'category' => 'developer',
            'configuration' => 'local-general',
            'prompt_template' => 'Generate documentation for the following TYPO3 code. Include:' . "\n" . '' . "\n" . '1. **Purpose**: What this code does' . "\n" . '2. **Usage**: How to use it (with examples)' . "\n" . '3. **Parameters/Properties**: Explanation of each' . "\n" . '4. **Return Values**: What to expect' . "\n" . '5. **Dependencies**: Required classes or extensions' . "\n" . '6. **Example**: Practical usage example' . "\n" . '' . "\n" . 'Code:' . "\n" . '```php' . "\n" . '{{input}}' . "\n" . '```' . "\n" . '' . "\n" . 'Format the documentation in RST (reStructuredText) format suitable for TYPO3 documentation.',
            'input_type' => 'manual',
            'input_source' => '',
            'output_format' => 'markdown',
            'is_active' => 1,
            'is_system' => 1,
            'sorting' => 330,
        ],
        [
            'identifier' => 'demo-extract-entities',
            'name' => 'Extract Entities',
            'description' => 'Demo task for the priced analytics stream.',
            'category' => 'content_ops',
            'configuration' => 'demo-cfg-gpt4o',
            'prompt_template' => '{input}',
            'input_type' => 'text',
            'input_source' => 'manual',
            'output_format' => 'text',
            'is_active' => 0,
            'is_system' => 0,
            'sorting' => 110,
        ],
        [
            'identifier' => 'demo-alt-text',
            'name' => 'Generate Alt Text',
            'description' => 'Demo task for the priced analytics stream.',
            'category' => 'content_ops',
            'configuration' => 'demo-cfg-gpt4o-mini',
            'prompt_template' => '{input}',
            'input_type' => 'text',
            'input_source' => 'manual',
            'output_format' => 'text',
            'is_active' => 0,
            'is_system' => 0,
            'sorting' => 120,
        ],
        [
            'identifier' => 'demo-describe-image',
            'name' => 'Describe Image',
            'description' => 'Demo task for the priced analytics stream.',
            'category' => 'content_ops',
            'configuration' => 'demo-cfg-claude',
            'prompt_template' => '{input}',
            'input_type' => 'text',
            'input_source' => 'manual',
            'output_format' => 'text',
            'is_active' => 0,
            'is_system' => 0,
            'sorting' => 130,
        ],
        [
            'identifier' => 'demo-translate',
            'name' => 'Translate Content',
            'description' => 'Demo task for the priced analytics stream.',
            'category' => 'content_ops',
            'configuration' => 'demo-cfg-gemini',
            'prompt_template' => '{input}',
            'input_type' => 'text',
            'input_source' => 'manual',
            'output_format' => 'text',
            'is_active' => 0,
            'is_system' => 0,
            'sorting' => 140,
        ],
    ],
];
