name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure provider '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: input
    id: typo3-version
    attributes:
      label: TYPO3 Version
      placeholder: "14.0.0"
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      placeholder: "8.5.0"
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: LLM Provider
      options:
        - OpenAI
        - Anthropic Claude
        - Google Gemini
        - Groq
        - Mistral
        - OpenRouter
        - Other
    validations:
      required: false
