<?php

declare(strict_types=1);

namespace Netresearch\NrLlm\Domain\Enum;

/**
 * Enum representing task output formats.
 *
 * Defines the format of the output generated by a task (markdown, JSON, etc.).
 */
enum TaskOutputFormat: string
{
    case MARKDOWN = 'markdown';
    case JSON = 'json';
    case PLAIN = 'plain';
    case HTML = 'html';

    /**
     * Get all output format values as an array.
     *
     * @return list<string>
     */
    public static function values(): array
    {
        return array_map(
            static fn(self $case): string => $case->value,
            self::cases(),
        );
    }

    /**
     * Check if a given string is a valid output format.
     */
    public static function isValid(string $value): bool
    {
        return in_array($value, self::values(), true);
    }

    /**
     * Try to create from string, returns null if invalid.
     */
    public static function tryFromString(string $value): ?self
    {
        return self::tryFrom($value);
    }

    /**
     * Get the content type for this output format.
     */
    public function getContentType(): string
    {
        return match ($this) {
            self::MARKDOWN => 'text/markdown',
            self::JSON => 'application/json',
            self::PLAIN => 'text/plain',
            self::HTML => 'text/html',
        };
    }

    /**
     * Get the file extension for this output format.
     */
    public function getFileExtension(): string
    {
        return match ($this) {
            self::MARKDOWN => 'md',
            self::JSON => 'json',
            self::PLAIN => 'txt',
            self::HTML => 'html',
        };
    }
}
