#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: Netresearch DTT GmbH

## Description: Copy landing page to web root
## Usage: copy-landing-page
## Example: ddev copy-landing-page

cp -f /tmp/landing-index.html /var/www/html/index.html
echo "Landing page copied to /var/www/html/index.html"
