<?php

/*
 * Copyright (c) 2025-2026 Netresearch DTT GmbH
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

declare(strict_types=1);

namespace Netresearch\NrLlm\Exception;

use Throwable;

/**
 * Marker for exceptions generated by nr_llm on its public API surface (ADR-053).
 *
 * Native parent catches remain compatible. Exceptions propagated from external
 * dependencies or consumer callbacks, and PHP engine errors, are not converted.
 * Catch tool-loop approval/input suspensions before this common failure marker
 * to retain their resumable state.
 *
 * @api
 */
interface NrLlmExceptionInterface extends Throwable {}
